# Generated by Django 5.2 on 2025-06-08 12:07

import applications.validators
import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="")),
                ("position", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="App",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("apk_file", models.FileField(upload_to="", verbose_name="فایل")),
                ("name", models.CharField(max_length=100, verbose_name="اسم")),
                ("subname", models.CharField(max_length=150, verbose_name="")),
                (
                    "icon_image",
                    models.ImageField(
                        height_field=800,
                        upload_to="",
                        validators=[applications.validators.validate_image_size],
                        verbose_name="",
                        width_field=800,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "در انتظار انتشار"),
                            ("published", "منتشر شده"),
                            ("deleted", "حذف شده"),
                        ],
                        default="draft",
                        max_length=30,
                        verbose_name="",
                    ),
                ),
                (
                    "legal_age",
                    models.PositiveSmallIntegerField(
                        validators=[applications.validators.validate_max_age],
                        verbose_name="",
                    ),
                ),
                ("downloads", models.PositiveIntegerField()),
                ("about", models.CharField(max_length=4000)),
                ("price", models.PositiveIntegerField()),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "Category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="applications.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AppImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                ("image_file", models.ImageField(upload_to="")),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="applications.app",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=3000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="applications.app",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
