# Generated by Django 5.2 on 2025-07-10 13:58

import applications.models
import applications.validators
import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("position", models.PositiveIntegerField()),
                (
                    "slug",
                    models.SlugField(allow_unicode=True, max_length=255, unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="App",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("apk_file", models.FileField(upload_to="")),
                ("name", models.CharField(max_length=100)),
                ("subname", models.CharField(max_length=150)),
                (
                    "icon_image",
                    models.ImageField(
                        upload_to="app-icons/",
                        validators=[applications.validators.validate_icon_image_size],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "در انتظار انتشار"),
                            ("published", "منتشر شده"),
                            ("deleted", "حذف شده"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                (
                    "legal_age",
                    models.PositiveSmallIntegerField(
                        validators=[applications.validators.validate_max_age]
                    ),
                ),
                ("downloads", models.PositiveIntegerField()),
                ("about", models.CharField(max_length=4000)),
                ("price", models.PositiveIntegerField()),
                (
                    "slug",
                    models.SlugField(allow_unicode=True, max_length=255, unique=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="apps",
                        to="applications.category",
                    ),
                ),
            ],
            options={
                "ordering": ("updated",),
            },
        ),
        migrations.CreateModel(
            name="AppImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "image_file",
                    models.ImageField(upload_to=applications.models.get_upload_to),
                ),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="applications.app",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=3000)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[applications.validators.validate_max_rate],
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="applications.app",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("updated",),
            },
        ),
    ]
