# Generated by Django 5.1 on 2025-06-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="app",
            old_name="Category",
            new_name="category",
        ),
        migrations.AlterField(
            model_name="app",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
