# Generated by Django 5.1 on 2025-06-12 09:44

import applications.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_rename_category_app_category_alter_app_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="icon_image",
            field=models.ImageField(
                upload_to="",
                validators=[applications.validators.validate_image_size],
                verbose_name="",
            ),
        ),
    ]
