# Generated by Django 5.2 on 2025-06-14 12:14

import applications.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_alter_app_icon_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, default=1, max_length=255, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, default=2, max_length=255, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="app",
            name="apk_file",
            field=models.FileField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="app",
            name="icon_image",
            field=models.ImageField(
                upload_to="", validators=[applications.validators.validate_image_size]
            ),
        ),
        migrations.AlterField(
            model_name="app",
            name="legal_age",
            field=models.PositiveSmallIntegerField(
                validators=[applications.validators.validate_max_age]
            ),
        ),
        migrations.AlterField(
            model_name="app",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "در انتظار انتشار"),
                    ("published", "منتشر شده"),
                    ("deleted", "حذف شده"),
                ],
                default="draft",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="app",
            name="subname",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=30),
        ),
    ]
