# Generated by Django 5.1 on 2025-07-01 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0004_app_slug_category_slug_alter_app_apk_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="apps",
                to="applications.category",
            ),
        ),
    ]
