# Generated by Django 5.1 on 2025-07-02 12:25

import applications.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0005_alter_app_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="rating",
            field=models.PositiveSmallIntegerField(
                default=1, validators=[applications.validators.validate_max_rate]
            ),
        ),
    ]
