# Generated by Django 5.2 on 2025-07-10 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="applications.app"
            ),
        ),
        migrations.AddField(
            model_name="bookmark",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
