# Generated by Django 5.1 on 2025-07-01 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_whistlist_whishlistitem"),
        ("applications", "0005_alter_app_category"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="WhistList",
            new_name="WishList",
        ),
        migrations.RenameModel(
            old_name="whishListItem",
            new_name="wishListItem",
        ),
        migrations.RenameField(
            model_name="wishlistitem",
            old_name="whishlist",
            new_name="wishlist",
        ),
    ]
