# Generated by Django 5.1 on 2025-07-02 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_rename_whistlist_wishlist_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wishlistitem",
            name="wishlist",
        ),
        migrations.AddField(
            model_name="wishlistitem",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="WishList",
        ),
    ]
