# Generated by Django 5.1 on 2025-07-03 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_remove_wishlistitem_wishlist_wishlistitem_user_and_more"),
        ("applications", "0006_review_rating"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="wishListItem",
            new_name="BookMark",
        ),
    ]
