# Generated by Django 5.1 on 2025-07-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_rename_wishlistitem_bookmark"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_developer",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=45, unique=True, verbose_name="نام کاربری"
            ),
        ),
    ]
